apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "basic-deployment.name" . }}
  labels:
    {{- include "basic-deployment.labels" . | nindent 4 }}
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  revisionHistoryLimit: 1
{{- if not .Values.keda.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "basic-deployment.selectorLabels" . | nindent 6 }}
  strategy:
    {{- with .Values.strategy }}
    {{- toYaml . | nindent 4 }}
    {{- end }}

  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "basic-deployment.selectorLabels" . | nindent 8 }}
    spec:
      initContainers:
      - name: init-config
        image: 637103254392.dkr.ecr.us-east-1.amazonaws.com/lyceum-cloud/busybox:latest
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'echo "Waiting for ConfigMap..." && sleep 20']          
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "basic-deployment.name" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- with .Values.hostAliases }}
      hostAliases:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Release.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.args }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- include "basic-deployment.env" . | nindent 10 }}
          {{- include "basic-deployment.envFrom" . | nindent 10 }}

          # {{ if not (eq (.Values.containerPort|int) 0) }}
          # ports:
          # - name: http
          #   containerPort: {{ .Values.containerPort|int }}
          #   protocol: TCP
          # {{- end }}
          ports:
          {{- range .Values.containerPorts }}          
            - name: {{ .name }}
              containerPort: {{ .containerPort }}
          {{- end }}
          livenessProbe: {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe: {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- include "basic-deployment.volumeMounts" . | nindent 10 }}
          {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- include "basic-deployment.volumes" . | nindent 6 }}
