{{- if .Values.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: monitoring
  name: {{ include "basic-deployment.name" . }}
  namespace: {{ include "basic-deployment.name" . }}
spec:
  endpoints:
  - interval: {{ .Values.serviceMonitor.interval | default "30s" }}
    targetPort: {{ .Values.serviceMonitor.targetPort | default "3000" }}
    path: {{ .Values.serviceMonitor.path | default "/metrics"  }}
  namespaceSelector:
    matchNames:
    - {{ include "basic-deployment.name" . }}
  selector:
    matchLabels:
      app: {{ include "basic-deployment.name" . }}
{{- end }}      