apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "basic-deployment.name" . }}
  namespace: {{ include "basic-deployment.name" . }}
  labels:
    app: {{ include "basic-deployment.name" . }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}