{{ if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "basic-deployment.name" . }}
  labels:
    {{- include "basic-deployment.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}    
spec:
  {{ if .Values.service.sessionAffinity.enabled -}}
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: {{ default 600 .Values.timeoutSeconds }}
  {{- end }}
  selector:
    app: {{ include "basic-deployment.name" . }}
  type: {{ .Values.service.type }}
  ports:
  {{- range .Values.service.ports }}          
    - name: {{ .name }}
      port: {{ .port }}
      {{- if .targetPort }}
      targetPort: {{ .targetPort }}
      {{- end }}
  {{- end }}     
  selector:
    {{- include "basic-deployment.selectorLabels" . | nindent 4 }}
{{- end }}



